root = "."
tmp_dir = "tmp"

[build]
 cmd = "go build -buildvcs=false -o tmp/main ."
 bin = "tmp/main"
 full_bin = "tmp/main"
 include_ext = ["go"]
 exclude_dir = ["tmp", "vendor"]

[log]
  level = "debug"

[color]
  # Customize each part's color. If no color found, use the raw app log.
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"
